version: '3.8'

services:
  api:
    build:
      context: ./api
      target: local
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=local
      - API_KEY=sample_api_key_123
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
